### PR TITLE
Add a GitHub action for building/packaging dist releases

### PR DESCRIPTION
**Pull request by mstenta**
This adds a GitHub action that will automatically run whenever a tag is pushed to the repo. It will run `npm install` and `npm run build` to create the `dist` folder, then it will create a `[module-name].tar.gz` tarball, and upload it to a new GitHub release draft.

This release was just created automatically in my fork as an example: https://github.com/mstenta/farm_precipitation/releases/tag/7.x-1.x-dev

Notably: this action can be reused in other field modules - it is not specific to `farm_precipitation`, so we can consider making it part of the official field module template or cookie-cutter generator in the future.

### CODE REVIEW

**Comment by jgaehring** [comment]
Ah this is brilliant!! Thanks, @mstenta!

I realized the other day that I already forgot to run a build on my latest commit before pushing it up to origin. And it's soooooo much nicer not to have to check in the `dist` folder. That just felt wrong.

So I'm trying to get up to speed on how this works, but perhaps you could tell me, does everything under the project root, including `dist`, get bundled up into the tarball? Or just the `dist` folder?

I assume it's the former. And if so, I wonder if it would make sense to restructure the PHP stuff, particularly so we're not necessarily including `src` files in the distribution package. Perhaps there are some best practices for how to do this in the Drupal world? Or perhaps it really doesn't matter?

**Comment by mstenta** [comment]
> So I'm trying to get up to speed on how this works, but perhaps you could tell me, does everything under the project root, including dist, get bundled up into the tarball? Or just the dist folder?

Yes, that's correct - the whole directory (including the `dist` folder) gets packaged into the tarball. The only exception is that the `node_modules` directory gets deleted first, so that doesn't get included.

> I wonder if it would make sense to restructure the PHP stuff, particularly so we're not necessarily including src files in the distribution package. Perhaps there are some best practices for how to do this in the Drupal world? Or perhaps it really doesn't matter?

Oh man! Ok... I'm having ideas... :-)

Let's do a quick call soon to brainstorm...

**Comment by jgaehring** [comment]
Ok, so we talked through a bunch of options yesterday, but here's what stuck out to me in particular.

There's lots more we could do with GitHub Actions, even going so far as to include nothing in this repository except the `src` directory and the `.github/workflows/release.yml` file, then publish a GitHub Action on their [Marketplace](https://help.github.com/en/actions/building-actions/publishing-actions-in-github-marketplace) which generates everything for us. The one problem with that is it precludes the possibility of running a build locally to test it out on local server before pushing out a release. At a quick glance, it appears there may be ways of setting up GitHub Actions to run locally, but it's unclear what kind of challenges that may pose.

I think a better option would be to set up an npm script that, in addition to running the Webpack build process, also runs a Node process for assembling the necessary PHP and Drupal files. We could include some custom settings in `package.json`, or have a separate `field-module.json` file, which could provide the details specific to that module, such as it's `name`, `label`, `description`, etc, which could get injected automatically into the boilerplate files. Ultimately, I'd love to have something like [`create-react-app`](https://create-react-app.dev/), where we could just have a script, which we publish to npm, then when the user runs it, it asks a few questions from the terminal and spits out a fully scaffolded project, without the need to maintain a special `field-module.json` file, and even the Webpack details would be hidden and rolled up into a single dependency, which they could just update periodically when they needed too.

Anyway, that's all great to have on the wishlist, and I think it will all be doable eventually, but for now, setting up this GitHub Action seems like a step in the right direction. I think there will probably be a sweet-spot between GH Actions (for the more CI/CD-side of things) and npm/Webpack (for project scaffolding and the build process itself). And it's important to differentiate what each of these tools does best, and not try to over-extend GH Actions to do too much of the build stuff, or force npm into handling continuous delivery. But I also think this PR puts us on the right track there.

So let's merge it in!

One other thought is, I haven't really bumped the version number since I started. We're still at 0.0.1 in the `package.json`, and I haven't tagged any commits. Maybe it's time to bump it to 0.1.0 just to get it started? Or is that premature?

**Comment by mstenta** [comment]
Thanks for summarizing all those thoughts @jgaehring !

I published the GitHub repo I sketched up for thinking through these ideas: https://github.com/mstenta/farm_client_module_template

And quoted you in this issue in particular: https://github.com/mstenta/farm_client_module_template/issues/5

I figure we can use that repo to discuss some of these ideas further, and perhaps evolve it into whatever the future solution needs to be (whether that be a GitHub template, a GitHub Action, NPM package(s), and/or a CLI script).

See the full list of issues for other ideas/considerations: https://github.com/mstenta/farm_client_module_template/issues

**Pull request merged**
